// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tech_software_engineer_consultant_int_backend.Models;

#nullable disable

namespace tech_software_engineer_consultant_int_backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251205150129_AjoutTables")]
    partial class AjoutTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<int>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.ActivationDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodeActivationId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUsage")
                        .HasColumnType("datetime2");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodeActivationId");

                    b.ToTable("ActivationDevices", (string)null);
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.BonDeLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GSMClient")
                        .HasColumnType("bigint");

                    b.Property<string>("MFClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTotalHTBL")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("MontantTotalTTCBL")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("NetHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietaireId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemiseBL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TitreClient")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BonDeLivraisons");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.BonDeSortie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebutCirculation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinCirculation")
                        .HasColumnType("datetime2");

                    b.Property<string>("ListeFacturesSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculeDeVoiture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceBS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BonDeSorties");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.CodeActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivationCodeReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedToEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedToPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessSector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxDevicesAllowed")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsersAllowed")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("CodeActivations");

                    b.HasDiscriminator<string>("Type").HasValue("CodeActivation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseAcheteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresseVendeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GSMAcheteur")
                        .HasColumnType("bigint");

                    b.Property<long>("GSMVendeur")
                        .HasColumnType("bigint");

                    b.Property<string>("ListIdsTransactions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MFAcheteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MFVendeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTotalHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTotalTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomAcheteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomVendeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietaireId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TitreAcheteur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.CompteBancaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClasseDeRisque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviseCompte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngagementTotal")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantBloque")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaireMensuel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Segmentation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoldeDisponible")
                        .HasColumnType("decimal(18, 5)");

                    b.HasKey("Id");

                    b.ToTable("CompteBancaires");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PortefeuilleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortefeuilleId");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Echeance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImpayeId")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("float");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Echeances");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<long>("GSMClient")
                        .HasColumnType("bigint");

                    b.Property<string>("ListeBLSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MFClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantHTFacture")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantTTCFacture")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietaireId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceFacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TitreClient")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Impaye", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Createdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datetombe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DossierId")
                        .HasColumnType("int");

                    b.Property<int?>("EcheanceId")
                        .HasColumnType("int");

                    b.Property<string>("Montant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbreImpaye")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefClt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Retard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DossierId");

                    b.HasIndex("EcheanceId")
                        .IsUnique()
                        .HasFilter("[EcheanceId] IS NOT NULL");

                    b.ToTable("Impayes");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.InventaireProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InventaireProduits");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.LoginRequest", b =>
                {
                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("LoginRequests");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDProduit")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.LotsTransactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdTransaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("RefLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LotsTransactions");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceiverGroupId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverGroupId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyNotif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateNotif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutNotif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Portefeuille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NbrDossiers")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portefeuilles");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Adresse_Image_Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sub_Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Rapport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PortefeuilleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortefeuilleId");

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.RapportJournalier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RapportsJournalier");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.RolePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RolePolicies");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.RolePolicyRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("RolePolicyId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("RoleId", "RolePolicyId");

                    b.HasIndex("RolePolicyId");

                    b.ToTable("RolePolicyRoles");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.SI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse_Image_SI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SIs");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Sequence", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NextValue")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.TransactionFinancière", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RapportJournalierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransactionsFinancières");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransactionFinancière");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PTHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PTTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityEntered")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceLot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeTransaction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Agence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Anciennete")
                        .HasColumnType("int");

                    b.Property<string>("Civilite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDeNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("DossierEncharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fonction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalité")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NombreDossier")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segmentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituationFamiliale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.UserGroupAssociation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroupAssociations");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.UserPortefeuilleAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PortefeuilleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortefeuilleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPortefeuilleAssociations");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<int>");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Abonnement", b =>
                {
                    b.HasBaseType("tech_software_engineer_consultant_int_backend.Models.CodeActivation");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DossierId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RenewalAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("DossierId");

                    b.HasIndex("UserId");

                    b.HasDiscriminator().HasValue("Abonnement");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Licence", b =>
                {
                    b.HasBaseType("tech_software_engineer_consultant_int_backend.Models.CodeActivation");

                    b.Property<string>("ActivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivationAttempts")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("UserId");

                    b.ToTable("CodeActivations", t =>
                        {
                            t.Property("IsActive")
                                .HasColumnName("Licence_IsActive");

                            t.Property("UserId")
                                .HasColumnName("Licence_UserId");
                        });

                    b.HasDiscriminator().HasValue("Licence");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Depense", b =>
                {
                    b.HasBaseType("tech_software_engineer_consultant_int_backend.Models.TransactionFinancière");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("RapportJournalierId");

                    b.HasDiscriminator().HasValue("Depense");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Recette", b =>
                {
                    b.HasBaseType("tech_software_engineer_consultant_int_backend.Models.TransactionFinancière");

                    b.Property<int>("PosteRecetteId")
                        .HasColumnType("int");

                    b.HasIndex("RapportJournalierId");

                    b.HasDiscriminator().HasValue("Recette");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.ActivationDevice", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.CodeActivation", "CodeActivation")
                        .WithMany("ActivationDevices")
                        .HasForeignKey("CodeActivationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeActivation");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Dossier", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Portefeuille", "Portefeuille")
                        .WithMany("ListeDossiers")
                        .HasForeignKey("PortefeuilleId");

                    b.Navigation("Portefeuille");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Impaye", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Dossier", "Dossier")
                        .WithMany("ListeImpayes")
                        .HasForeignKey("DossierId");

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Echeance", "Echeance")
                        .WithOne("Impaye")
                        .HasForeignKey("tech_software_engineer_consultant_int_backend.Models.Impaye", "EcheanceId");

                    b.Navigation("Dossier");

                    b.Navigation("Echeance");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Message", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Group", "ReceiverGroup")
                        .WithMany("MessagesList")
                        .HasForeignKey("ReceiverGroupId");

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceiverGroup");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Notification", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "User")
                        .WithMany("ListeNotifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Rapport", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Portefeuille", "Portefeuille")
                        .WithMany("ListeRapports")
                        .HasForeignKey("PortefeuilleId");

                    b.Navigation("Portefeuille");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.RolePolicyRole", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Role", "Role")
                        .WithMany("RolePolicyRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.RolePolicy", "RolePolicy")
                        .WithMany("RolePolicyRoles")
                        .HasForeignKey("RolePolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("RolePolicy");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.User", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.UserGroupAssociation", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Group", "Group")
                        .WithMany("UserGroupAssociations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "User")
                        .WithMany("UserGroupAssociations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.UserPortefeuilleAssociation", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Portefeuille", "Portefeuille")
                        .WithMany("UserPortefeuilleAssociations")
                        .HasForeignKey("PortefeuilleId");

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "User")
                        .WithMany("ListeUserPortefeuilles")
                        .HasForeignKey("UserId");

                    b.Navigation("Portefeuille");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.UserRole", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Abonnement", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.Dossier", null)
                        .WithMany("ListeAbonnements")
                        .HasForeignKey("DossierId");

                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "User")
                        .WithMany("Abonnements")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Licence", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.User", "User")
                        .WithMany("Licences")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Depense", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.RapportJournalier", "RapportJournalier")
                        .WithMany("Depenses")
                        .HasForeignKey("RapportJournalierId");

                    b.Navigation("RapportJournalier");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Recette", b =>
                {
                    b.HasOne("tech_software_engineer_consultant_int_backend.Models.RapportJournalier", "RapportJournalier")
                        .WithMany("Recettes")
                        .HasForeignKey("RapportJournalierId");

                    b.Navigation("RapportJournalier");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.CodeActivation", b =>
                {
                    b.Navigation("ActivationDevices");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Dossier", b =>
                {
                    b.Navigation("ListeAbonnements");

                    b.Navigation("ListeImpayes");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Echeance", b =>
                {
                    b.Navigation("Impaye");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Group", b =>
                {
                    b.Navigation("MessagesList");

                    b.Navigation("UserGroupAssociations");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Portefeuille", b =>
                {
                    b.Navigation("ListeDossiers");

                    b.Navigation("ListeRapports");

                    b.Navigation("UserPortefeuilleAssociations");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.RapportJournalier", b =>
                {
                    b.Navigation("Depenses");

                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.Role", b =>
                {
                    b.Navigation("RolePolicyRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.RolePolicy", b =>
                {
                    b.Navigation("RolePolicyRoles");
                });

            modelBuilder.Entity("tech_software_engineer_consultant_int_backend.Models.User", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Licences");

                    b.Navigation("ListeNotifications");

                    b.Navigation("ListeUserPortefeuilles");

                    b.Navigation("MessagesSent");

                    b.Navigation("UserGroupAssociations");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
